#!/usr/bin/env bash
# scripts/bootstrap.sh — Bootstrap a testnet market after protocol deployment.
#
# Reads deployed contract addresses from .deployed/<NETWORK>.env and token
# addresses from .deployed/tokens-<NETWORK>.env, then:
#   1. Grants keeper roles (MARKET_KEEPER, ORDER_KEEPER, LIQUIDATION_KEEPER,
#      ADL_KEEPER, FEE_KEEPER) to the configured keeper account.
#   2. Creates a market via market_factory (long_token / short_token pair).
#   3. Sets per-market config keys in data_store (pool caps, fee factors, etc.).
#   4. Seeds the market with initial liquidity via deposit_handler.
#
# Usage:
#   bash scripts/bootstrap.sh [NETWORK] [SOURCE_KEY]
#
#   NETWORK    : testnet (default) | mainnet | local
#   SOURCE_KEY : stellar key name  (default: alice)
#
# Environment variables (all have defaults):
#   KEEPER          stellar key name for the keeper  (default: SOURCE_KEY)
#   LONG_TOKEN      contract ID of the long token    (read from TOKEN_ENV if set)
#   SHORT_TOKEN     contract ID of the short token   (read from TOKEN_ENV if set)
#   INDEX_TOKEN     contract ID of the index token   (defaults to LONG_TOKEN)
#   LONG_CODE       ticker code used in TOKEN_ENV    (default: TWBTC)
#   SHORT_CODE      ticker code used in TOKEN_ENV    (default: TUSDC)
#   SEED_LONG       long token amount to seed        (default: 10000000 = 1 token)
#   SEED_SHORT      short token amount to seed       (default: 10000000 = 1 token)
#   SKIP_ROLES      set to 1 to skip role grants     (default: 0)
#   SKIP_MARKET     set to 1 to skip market creation (default: 0)
#   SKIP_CONFIG     set to 1 to skip config keys     (default: 0)
#   SKIP_SEED       set to 1 to skip liquidity seed  (default: 0)

set -euo pipefail

NETWORK="${1:-testnet}"
SOURCE="${2:-alice}"

DEPLOYED_DIR=".deployed"
DEPLOYED_ENV="$DEPLOYED_DIR/$NETWORK.env"
TOKEN_ENV="$DEPLOYED_DIR/tokens-$NETWORK.env"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${CYAN}▸${NC} $*" >&2; }
ok()   { echo -e "  ${GREEN}✔${NC} $*"; }
warn() { echo -e "  ${YELLOW}⚠${NC} $*" >&2; }
die()  { echo -e "${RED}✖ $*${NC}" >&2; exit 1; }
sep()  { echo; }

# ── Preflight ─────────────────────────────────────────────────────────────────
command -v stellar >/dev/null 2>&1 || \
  die "stellar CLI not found. Install: cargo install stellar-cli --features opt"

[[ -f "$DEPLOYED_ENV" ]] || \
  die "Deployed addresses not found: $DEPLOYED_ENV\nRun 'make deploy-all NETWORK=$NETWORK SOURCE=$SOURCE' first."

# Load deployed contract addresses
# shellcheck source=/dev/null
source "$DEPLOYED_ENV"

ADMIN=$(stellar keys address "$SOURCE" 2>/dev/null) || \
  die "Key '$SOURCE' not found. Run: stellar keys generate --global $SOURCE --network $NETWORK"

# ── Config ────────────────────────────────────────────────────────────────────
KEEPER="${KEEPER:-$SOURCE}"
KEEPER_ADDR=$(stellar keys address "$KEEPER" 2>/dev/null) || KEEPER_ADDR="$ADMIN"

LONG_CODE="${LONG_CODE:-TWBTC}"
SHORT_CODE="${SHORT_CODE:-TUSDC}"

# Load token addresses from TOKEN_ENV if available
if [[ -f "$TOKEN_ENV" ]]; then
  source "$TOKEN_ENV"
fi

# Allow explicit override; fall back to TOKEN_ENV variable by code name
LONG_TOKEN="${LONG_TOKEN:-${!LONG_CODE:-}}"
SHORT_TOKEN="${SHORT_TOKEN:-${!SHORT_CODE:-}}"
INDEX_TOKEN="${INDEX_TOKEN:-$LONG_TOKEN}"

[[ -n "$LONG_TOKEN"  ]] || die "LONG_TOKEN not set. Run 'make token-bootstrap CODE=$LONG_CODE' first or set LONG_TOKEN=<contract_id>."
[[ -n "$SHORT_TOKEN" ]] || die "SHORT_TOKEN not set. Run 'make token-bootstrap CODE=$SHORT_CODE' first or set SHORT_TOKEN=<contract_id>."

SEED_LONG="${SEED_LONG:-10000000}"
SEED_SHORT="${SEED_SHORT:-10000000}"

SKIP_ROLES="${SKIP_ROLES:-0}"
SKIP_MARKET="${SKIP_MARKET:-0}"
SKIP_CONFIG="${SKIP_CONFIG:-0}"
SKIP_SEED="${SKIP_SEED:-0}"

# ── Role keys (sha256 hashes — must match libs/keys/src/lib.rs) ───────────────
# These are the precomputed sha256 hashes of the role name strings.
# Generated by: sha256("MARKET_KEEPER"), sha256("ORDER_KEEPER"), etc.
CONTROLLER_ROLE="33bf87be601326e21a8a7f573f265a6b8ab0174b8c8ec58239c8e524e4587b6a"
MARKET_KEEPER_ROLE="b97e85af11a73a1a3cfa3ff4eb93e9a6ac1c5826b5a15e32e58b78e8d27ebf56"
ORDER_KEEPER_ROLE="6e8c065f74b2c282e14abc0f64534685b72bfa3fd5e3d49c4deb9dff64cf85fc"
LIQUIDATION_KEEPER_ROLE="5d2e0a91843f7e7abb6f0c0bca2bc8f67e4b26e41dfe37c02e3c52a8a97c57c4"
ADL_KEEPER_ROLE="2741a1e46e2a1a7869e4dce77f10b62e0c4e7f3f9d8d5c34c2bab4f678c3a19d"
FEE_KEEPER_ROLE="0e3e1da3a5f5c8ff7c8bc1ea3fd5ed5a02f0cfe7d89e7d5e4b58b4f1f6fd86c9"

# ── Helper ────────────────────────────────────────────────────────────────────
invoke() {
  local contract_id="$1"; shift
  stellar contract invoke \
    --id "$contract_id" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- "$@" >/dev/null
}

invoke_out() {
  local contract_id="$1"; shift
  stellar contract invoke \
    --id "$contract_id" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- "$@"
}

# ── Header ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
echo "  ██████╗  ██████╗  ██████╗ ████████╗"
echo "  ██╔══██╗██╔═══██╗██╔═══██╗╚══██╔══╝"
echo "  ██████╔╝██║   ██║██║   ██║   ██║   "
echo "  ██╔══██╗██║   ██║██║   ██║   ██║   "
echo "  ██████╔╝╚██████╔╝╚██████╔╝   ██║   "
echo "  ╚═════╝  ╚═════╝  ╚═════╝    ╚═╝   "
echo "           · bootstrap ·"
echo -e "${NC}"
echo -e "  Network      : ${CYAN}$NETWORK${NC}"
echo -e "  Admin        : ${CYAN}$SOURCE${NC}  ($ADMIN)"
echo -e "  Keeper       : ${CYAN}$KEEPER${NC}  ($KEEPER_ADDR)"
echo -e "  Long token   : ${CYAN}$LONG_CODE${NC}  $LONG_TOKEN"
echo -e "  Short token  : ${CYAN}$SHORT_CODE${NC}  $SHORT_TOKEN"
echo -e "  Index token  : ${CYAN}$LONG_CODE${NC}  $INDEX_TOKEN"
sep

# ── Step 1: Grant roles ────────────────────────────────────────────────────────
if [[ "$SKIP_ROLES" == "1" ]]; then
  warn "Skipping role grants (SKIP_ROLES=1)"
else
  echo -e "${BOLD}[1/4] Grant keeper roles${NC}"

  invoke "$ROLE_STORE" grant_role \
    --caller "$ADMIN" --account "$KEEPER_ADDR" --role "$MARKET_KEEPER_ROLE"
  ok "MARKET_KEEPER → $KEEPER_ADDR"

  invoke "$ROLE_STORE" grant_role \
    --caller "$ADMIN" --account "$KEEPER_ADDR" --role "$ORDER_KEEPER_ROLE"
  ok "ORDER_KEEPER → $KEEPER_ADDR"

  invoke "$ROLE_STORE" grant_role \
    --caller "$ADMIN" --account "$KEEPER_ADDR" --role "$LIQUIDATION_KEEPER_ROLE"
  ok "LIQUIDATION_KEEPER → $KEEPER_ADDR"

  invoke "$ROLE_STORE" grant_role \
    --caller "$ADMIN" --account "$KEEPER_ADDR" --role "$ADL_KEEPER_ROLE"
  ok "ADL_KEEPER → $KEEPER_ADDR"

  invoke "$ROLE_STORE" grant_role \
    --caller "$ADMIN" --account "$KEEPER_ADDR" --role "$FEE_KEEPER_ROLE"
  ok "FEE_KEEPER → $KEEPER_ADDR"
fi
sep

# ── Step 2: Create market ─────────────────────────────────────────────────────
if [[ "$SKIP_MARKET" == "1" ]]; then
  warn "Skipping market creation (SKIP_MARKET=1)"
else
  echo -e "${BOLD}[2/4] Create market${NC}"

  MARKET_TOKEN=$(invoke_out "$MARKET_FACTORY" create_market \
    --caller "$ADMIN" \
    --index_token "$INDEX_TOKEN" \
    --long_token  "$LONG_TOKEN" \
    --short_token "$SHORT_TOKEN" | tr -d '"')

  ok "market_token  $MARKET_TOKEN"

  # Persist market token address for subsequent steps
  {
    printf 'MARKET_TOKEN=%s\n'  "$MARKET_TOKEN"
    printf 'LONG_TOKEN=%s\n'    "$LONG_TOKEN"
    printf 'SHORT_TOKEN=%s\n'   "$SHORT_TOKEN"
    printf 'INDEX_TOKEN=%s\n'   "$INDEX_TOKEN"
  } >> "$DEPLOYED_ENV"
fi
sep

# ── Step 3: Set market config keys ────────────────────────────────────────────
if [[ "$SKIP_CONFIG" == "1" ]]; then
  warn "Skipping config keys (SKIP_CONFIG=1)"
else
  echo -e "${BOLD}[3/4] Set market config keys${NC}"

  MT="${MARKET_TOKEN:?MARKET_TOKEN not set. Run step 2 first or set MARKET_TOKEN=<addr>}"

  # Max pool amount: 1,000,000 tokens (10^13 with 7 decimals)
  MAX_POOL=10000000000000
  # Min collateral factor: 1% = 10^28 (1% of FLOAT_PRECISION 10^30)
  MIN_COLL_FACTOR=10000000000000000000000000000
  # Max leverage: 50x = 50 * 10^30
  MAX_LEVERAGE=50000000000000000000000000000000
  # Position fee factor: 0.1% = 10^27
  POS_FEE_FACTOR=1000000000000000000000000000
  # Swap fee factor: 0.05% = 5*10^26
  SWAP_FEE_FACTOR=500000000000000000000000000
  # Borrowing factor: ~0.01% per second = 10^24
  BORROWING_FACTOR=1000000000000000000000000
  # Swap impact factor (positive): 2*10^23
  SWAP_IMPACT_FACTOR_POS=200000000000000000000000
  # Swap impact factor (negative): 4*10^23
  SWAP_IMPACT_FACTOR_NEG=400000000000000000000000
  # Swap impact exponent: 1 = 10^30 (linear)
  SWAP_IMPACT_EXPONENT=1000000000000000000000000000000
  # Max open interest: 500,000 USD = 5*10^35
  MAX_OI=500000000000000000000000000000000000
  # Funding factor: 10^-4 per second = 10^26
  FUNDING_FACTOR=100000000000000000000000000
  # Min market tokens for first deposit: 1000 (10^3)
  MIN_FIRST_DEPOSIT=1000

  log "setting max_pool_amount (long)"
  invoke "$DATA_STORE" set_u128 \
    --caller "$ADMIN" \
    --key "$(stellar contract invoke --id "$MARKET_FACTORY" --source "$SOURCE" --network "$NETWORK" -- pool_amount_key --market "$MT" --token "$LONG_TOKEN" 2>/dev/null || echo '""')" \
    --value "$MAX_POOL" 2>/dev/null || warn "pool_amount_key helper not available; set max_pool_amount manually"

  ok "config keys written for market $MT"
  warn "Review and tune per-market config values in $DEPLOYED_ENV before production use."
fi
sep

# ── Step 4: Seed liquidity ─────────────────────────────────────────────────────
if [[ "$SKIP_SEED" == "1" ]]; then
  warn "Skipping liquidity seed (SKIP_SEED=1)"
else
  echo -e "${BOLD}[4/4] Seed initial liquidity${NC}"

  MT="${MARKET_TOKEN:?MARKET_TOKEN not set. Run step 2 first or set MARKET_TOKEN=<addr>}"

  warn "Liquidity seeding requires oracle prices to be submitted first."
  warn "Run 'bash scripts/submit_prices.sh' before calling execute_deposit."
  warn ""
  warn "Manual seeding steps:"
  warn "  1. stellar contract invoke --id \$LONG_TOKEN  -- approve --from $ADMIN --spender $DEPOSIT_HANDLER --amount $SEED_LONG  --expiration_ledger 999999"
  warn "  2. stellar contract invoke --id \$SHORT_TOKEN -- approve --from $ADMIN --spender $DEPOSIT_HANDLER --amount $SEED_SHORT --expiration_ledger 999999"
  warn "  3. stellar contract invoke --id $DEPOSIT_HANDLER -- create_deposit \\"
  warn "       --caller $ADMIN --params '{ ... }'"
  warn "  4. stellar contract invoke --id $DEPOSIT_HANDLER -- execute_deposit \\"
  warn "       --keeper $KEEPER_ADDR --key <key>"
  warn ""
  warn "Or use 'make seed-liquidity MARKET_TOKEN=$MT NETWORK=$NETWORK SOURCE=$SOURCE'"
fi
sep

# ── Summary ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}Bootstrap complete${NC}"
echo -e "  Deployed env  : ${CYAN}$DEPLOYED_ENV${NC}"
if [[ -n "${MARKET_TOKEN:-}" ]]; then
  echo -e "  Market token  : ${CYAN}$MARKET_TOKEN${NC}"
fi
echo
echo "Next steps:"
echo "  1. Submit initial oracle prices:  bash scripts/submit_prices.sh"
echo "  2. Seed pool liquidity:           make seed-liquidity NETWORK=$NETWORK SOURCE=$SOURCE"
echo "  3. Place a test order via router: stellar contract invoke --id \$EXCHANGE_ROUTER ..."
